[db]
port = 5432
major_version = 15
project_id = "calculator"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://calculator-akito.vercel.app"
additional_redirect_urls = ["https://calculator-akito.vercel.app"]
jwt_expiry = 3600
enable_signup = true 