name: Performance Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜日に実行

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ secrets.PRODUCTION_URL }}
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Run k6 Load Test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: tests/performance/load-test.js
